name: NodeJS with Webpack

on:
  push:
    branches: [ main, init ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Build
      run: |
        npm install
        npm run build

    - name: Archive
      run: |
        touch artifact.tar && tar --dereference --hard-dereference -cvf artifact.tar build --exclude=.git --exclude=artifact.tar 

    - name: Upload artifact
      uses: actions/upload-artifact@main
      with:
        name: github-pages
        path: ./artifact.tar
        if-no-files-found: warn

    # - name: Deploy
    #   uses: JamesIves/github-pages-deploy-action@v4.2.2
    #   with:
    #     branch: gh-pages
    #     folder: build

    # - name: setup git
    #   run: |
    #     git config user.name "GitHub Actions Bot"
    #     git config user.email "<>"

    # - name: commit
    #   run: |
    #     # Stage the file, commit and push
    #     git add -f build
    #     git commit -m "pages"
    #     git push origin gh-pages  
  
    # - name: Upload artifact for deployment job
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: node-app
    #     path: build
  
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: node-app

  #   - name: setup git
  #     run: |
  #       git config user.name "GitHub Actions Bot"
  #       git config user.email "<>"

  #   - name: commit
  #     run: |
  #       # Stage the file, commit and push
  #       git add build
  #       git commit -m "pages"
  #       git push origin gh-pages

  #   - name: Pre Deploy to GitHub Pages
  #     uses: actions/deploy-pages@v1-beta
  #     with:
  #       token: ${{ github.token }}
  #       timeout: 600000
  #       error_count: 10
  #       reporting_interval: 1000

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v1-beta
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        timeout: 600000
        error_count: 10
        reporting_interval: 1000

